---

- name: '[DEBUG] package'
  ansible.builtin.debug:
    var: package
  tags: [never, debug]

- name: Install {{ item.name }}
  community.general.homebrew:
    name: foo
    state: present

- name: "[Post install]"
  include_tasks: ../post_install/main.yml
  vars:
    params: '{{ package.post_install }}'
  when: package.post_install is defined

