---

- name: '[DEBUG] package'
  ansible.builtin.debug:
    var: package
  tags: [never, debug]

- name: Install
  community.general.snap:
    name:
      - '{{package.name}}'
    classic: '{{package.classic}}'

- name: "[Post install]"
  include_tasks: ../post_install/main.yml
  vars:
    params: '{{ package.post_install }}'
  when: package.post_install is defined