- name: local
  hosts: all
  become: yes
  become_user: root
  vars_files:
    - vars/packages.yml
    - vars/config.yml

  roles:
    - { role: common }
    - { role: ansible }

- name: vagrant
  hosts: vagrant
  become: yes
  become_user: vagrant

  roles:
    - { role: vagrant_test }
