---

- name: Update apt
  become: yes
  become_user: root
  apt: update_cache=yes cache_valid_time="{{ config.apt.cache_ttl }}"

- name: Upgrade apt
  apt: upgrade=yes

- name: Normalize apt packages params
  ansible.builtin.set_fact:
    apt_packages: []
  when: apt.packages is defined
- name: Normalize apt packages params
  ansible.builtin.set_fact:
    apt_packages: "{{ apt_packages | default([]) | union([ (item is mapping) | ternary(item, {'name': item}) ])}}"
  with_items: "{{apt.packages}}"
  when: apt.packages is defined

- name: Install packages
  include_tasks: _apt_package.yml
  with_items: "{{ apt_packages }}"
  loop_control:
    label: "{{ package.name }}"
    loop_var: package

- name: Install from third party repos
  include_tasks: _apt_repo.yml
  with_items: "{{ apt.repos }}"
  loop_control:
    label: "{{ repo.repo }}"
    loop_var: repo
  when: apt.repos is defined
